config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      post 'step2',    to:'signup#save_to_session_step1'
      get 'step3'
      post 'step3',    to:'signup#save_to_session_step2'
      get 'step4'
      post 'step4',    to:'signup#save_to_session_step3'
      get 'done'
    end
  end
  root to: 'items#index'

  resources :items do
    resources :purchase, only: :show do
      member do
        post "pay", to: 'purchase#pay'
      end
    end
  end


  resources :users do
    member do
      get "logout"
      get "profile"
      get "userinfo"
      get "cardlist"
    end
  end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  require 'payjp'
  
  def step1
    @user = User.new
  end

  def step2
    @user = User.new
  end

  def step3
    @address = Address.new
  end

  def step4
    @card = Card.new
  end

  def done
    sign_in User.find(session[:id]) unless user_signed_in? 
  end

  #一括保存
  def create
    @user = User.new(
    nickname: session[:nickname],
    email: session[:email],
    password: session[:password],
    password_confirmation: session[:password_confirmation],
    family_name: session[:family_name],
    first_name: session[:first_name],
    family_name_kana: session[:family_name_kana],
    first_name_kana: session[:first_name_kana],
    birthdate_year: session[:birthdate_year],
    birthdate_month: session[:birthdate_month],
    birthdate_day: session[:birthdate_day]
    )

    unless @user.save
      reset_session
      redirect_to step1_signup_index_path
    end

    if session[:provider].present?
      @snscredential = SnsCredential.create(
        user: @user,
        uid: session[:uid],
        provider: session[:provider]
      )
  end

    @address = Address.create(
      user: @user,
      postal_code: session[:postal_code],
      prefecture_id: session[:prefecture_id],
      city: session[:city],
      house_number: session[:house_number],
      building_name: session[:building_name],
      phone_number: session[:phone_number]
    )
    Payjp.api_key = ENV['PAYJP_TEST_SECRET_KEY']
    customer = Payjp::Customer.create(card: params['payjp-token'])
    @card = Card.new(
      user: @user,
      customer_id: customer.id,
      card_id: customer.default_card
    )

    if @card.save
      reset_session
      session[:id] = @user.id
      redirect_to done_signup_index_path
    else
      reset_session
      redirect_to step1_signup_index_path
    end
  end

  def save_to_session_step1
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    if session[:provider].blank?
      session[:password] = user_params[:password]
      session[:password_confirmation] = user_params[:password_confirmation]
    end
    session[:family_name] = user_params[:family_name]
    session[:first_name] = user_params[:first_name]
    session[:family_name_kana] = user_params[:family_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    session[:birthdate_year] = user_params[:birthdate_year]
    session[:birthdate_month] = user_params[:birthdate_month]
    session[:birthdate_day] = user_params[:birthdate_day]
    redirect_to step2_signup_index_path
  end

  def save_to_session_step2
    #session[:phone_number] = user_params[:phone_number]
    redirect_to step3_signup_index_path
  end

  def save_to_session_step3
    session[:postal_code] = address_params[:postal_code]
    session[:prefecture_id] = address_params[:prefecture_id]
    session[:city] = address_params[:city]
    session[:house_number] = address_params[:house_number]
    session[:building_name] = address_params[:building_name]
    session[:phone_number] = address_params[:phone_number]
    redirect_to step4_signup_index_path
  end

  private
  
    def user_params
      params.require(:user).permit(
        :nickname,
        :email,
        :password,
        :password_confirmation,
        :family_name,
        :first_name,
        :family_name_kana,
        :first_name_kana,
        :birthdate_year,
        :birthdate_month,
        :birthdate_day
      )
    end

    def address_params
      params.require(:address).permit(
        :postal_code,
        :prefecture_id,
        :city,
        :house_number,
        :building_name,
        :phone_number
      )
    end

end

app/views/signup/_user_footer.html.haml
.single-footer
  %nav
    %ul 
      %li
        %a{href: '#'} プライバシーポリシー
      %li
        %a{href: '#'} メルカリ利用規約
      %li
        %a{href: '#'} 特定商品に関する表記
    -# %img{src:'logo_gray.svg', class:"footer-icon"}
    = image_tag 'logo_gray.svg', class: 'footer-icon'
  %p
    %small  ©️2019 fmarket,Inc.

app/views/signup/_user_header.html.haml
.users_s1_header
  %h1
    %a{href: '#'}
      = image_tag 'fmarket_logo_red.svg', alt: "Fmarket", class: 'header-logo'

  %nav.progress-bar-navi
    .header-progress-bar-wrap 
      %p#progress-bar_step1 会員情報 
      %span.progress-radius.first#step1

    .header-progress-bar-wrap
      %p#progress-bar_step2 電話番号認証
      %span.progress_radius#step2

    .header-progress-bar-wrap
      %p#progress-bar_step3 お届け先住所入力
      %span.progress_radius#step3

    .header-progress-bar-wrap
      %p#progress-bar_step4 支払い方法
      %span.progress_radius#step4

    .header-progress-bar-wrap
      %p#progress-bar_done 完了
      %span.progress_radius.last#done

app/views/signup/done.html.haml
= render "user_header"
.single-main
  %p.register-head 会員登録完了
  .register-form
    .form
      .end
        %p ありがとうございます。
        %p 会員登録が完了しました。
    .form
      .next-btn
      = link_to items_path do
        %button{type:"submit",class:"btn-red"}
          メルカリをはじめる 
.single-footer.last-page-footer
  %nav
    %ul 
      %li
        %a{href: '#'} プライバシーポリシー
      %li
        %a{href: '#'} メルカリ利用規約
      %li
        %a{href: '#'} 特定商品に関する表記
    -# %img{src:'logo_gray.svg', class:"footer-icon"}
    = image_tag 'logo_gray.svg', class: 'footer-icon'
  %p
    %small  ©️2019 fmarket,Inc.

app/views/signup/index.html.haml
-# = link_to 'メールで新規登録', step1_signup_index_path, method: :get,  class: 'signup__btn'

.signup-index-page
  = render 'items/header.new'
  .signup-index-page-main
    .main__header
      %h1 新規会員登録
    .main
      = link_to step1_signup_index_path, class: 'mail-registration-btn' do
        %i.far.fa-envelope
        メールアドレスで登録する
      = link_to user_facebook_omniauth_authorize_path, class: 'facebook-registration-btn' do
        %i.fab.fa-facebook-square
        Facebookで登録する
      = link_to user_google_oauth2_omniauth_authorize_path, class: 'google-registration-btn' do
        %i.fab.fa-google
        Googleで登録する
  = render 'signup/user_footer'

app/views/signup/step1.html.haml
= render "user_header"

%main.single-main-1st
  .register-head
    %h2 会員情報入力
  .register-form-1st
    = form_for @user, url: step2_signup_index_path, method: :post do |f|
      .form
        = f.label :nickname, 'ニックネーム', class: 'form-label'
        %span.form-require
        = f.text_field :nickname, class: 'form-input', placeholder: '例) メルカリ太郎', value: session[:nickname]

      .form
        = f.label :email, 'メールアドレス', class: 'form-label'
        %span.form-require
        = f.email_field :email, class: 'form-input', placeholder: 'PC・携帯どちらでも可', value: session[:email]

      - if session[:provider].blank?
        .form.password
          = f.label :password, 'パスワード', class: 'form-label'
          %span.form-require
          = f.password_field :password, class: 'form-input', placeholder: '7文字以上の半角英数字'
          %p.form-info ※ 英字と数字の両方を含めて設定してください
          %input{type:"checkbox", class:"check"} パスワードを表示する

      .form
        %h3 本人確認
        %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。

      .form
        = f.label :family_name, 'お名前(全角)', class: 'form-label-half'
        %span.form-require
        = f.text_field :family_name, class: 'form-input-half', placeholder: '例）山田'
        = f.text_field :first_name, class: 'form-input-half', placeholder: '例）彩'

      .form
        = f.label :family_name_kana, 'お名前カナ(全角)', class: 'form-label-half'
        %span.form-require
        = f.text_field :family_name_kana, class: 'form-input-half', placeholder: '例）ヤマダ'
        = f.text_field :first_name_kana, class: 'form-input-half', placeholder: '例）アヤ'

      .form
        = f.label :birthday, '生年月日', class: 'form-label'
        %span.form-require
        .birthday-select
          = f.select :birthdate_year, options_for_select(1900..2019), include_blank: '--', class: "birthday"
          %span 年
          = f.select :birthdate_month, options_for_select(1..12), include_blank: '--', class: "birthday"
          %span 月
          = f.select :birthdate_day, options_for_select(1..31), include_blank: '--', class: "birthday"
          %span 日

      .form.info
        %p.form-info  
          ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。

      .form
        .recaptcha-check
          %input{type:"checkbox", class:"recaptcha"} 私はロボットではありません

      .form
        %p
        「次へ進む」のボタンを押すことにより、
        %a{href: '#'} 利用規約
        に同意したものとみなします
        .next-btn
          %button{type:"submit",class:"btn-red"}
            次へ進む

      .form
        %p.single-text
          %a{href: '#'} 本人情報の登録について

= render "user_footer"

app/views/signup/step2.html.haml
= render "user_header"

.call__content
  .contents
    .content
      .content__head
        %p 電話番号の確認
      .content__box
        .content__boxes
          .content__form  
            %label{class: "label__title"} 携帯電話の番号
            %input{placeholder: "携帯電話の番号入力", class: "input__form"}
          %p
            本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          = link_to step3_signup_index_path, method: :post, class: 'content__btn' do
            SMSを送信する
          %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .content__bottom
            =link_to '#' do
              電話番号が必要な理由
              .i-class
                >
= render "user_footer"

app/views/signup/step3.html.haml
= render "user_header"

%main.single-main
  .register-head お届け先住所入力
  .register-form
    = form_for @address, url: step4_signup_index_path, method: :post do |f|
      .form
        = f.label :postal_code, '郵便番号', class: 'form-label'
        %span.form-require 
        = f.text_field :postal_code, placeholder: "例）123-4567", class: 'form-input'
      .form
        = f.label :prefecture_id, '都道府県', class: 'form-label'
        %span.form-require 
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name, class: 'form-input', prompt: "---"
      .form  
        = f.label :city, '市区町村', class: 'form-label'
        %span.form-require 
        = f.text_field :city, placeholder: "市区町村", class: 'form-input'
      .form
        = f.label :house_number, '番地', class: 'form-label'
        %span.form-require 
        = f.text_field :house_number, placeholder: "例）青山1-1-1", class: 'form-input'
      .form
        = f.label :building_name, '建物名', class: 'form-label'
        %span.form-require--gray 
        = f.text_field :building_name, placeholder: "例）柳ビル103", class: 'form-input'
      -#.form
        = f.label :phone_number, '携帯電話の番号', class: 'form-label'
        %span.form-require--gray 
        = f.text_field :phone_number, placeholder: "例）09012345678", class: 'form-input'
      .form
        .next-btn
          %button{type:"submit",class:"btn-red"}
            登録する

= render 'user_footer'

app/views/signup/step4.html.haml
= render "user_header"

.call__content
  .contents
    .content
      .content__head
        %p 支払い方法
      .content__boxtt
        .content__boxestt
          .content__formtt
            = form_with url: signup_index_path, method: :post, html: { name: "inputForm" } do |f|
              = f.label :card_number, 'カード番号', class: 'label__title'
              %span{class: "form__text"} 必須
              = f.text_field :card_number, type: 'text', class: 'input__form', placeholder: '半角数字のみ'

              %ul.card__icon
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2356214421", width: "49", height: "20" 
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2356214421", width:"34", height:"20"
                %li  
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2356214421", width:"30", height:"20"
                %li  
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2356214421", width:"32", height:"20"
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2356214421", width:"21", height:"20"
                %li
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2356214421", width:"32", height:"20"
                %li  
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2356214421", width:"32", height:"20"

                .content__limit
                  %label{class: "label__title"} 有効期限
                  %span{class: "form__text"} 必須
                  %br

                  .content__select
                    = f.select :exp_month,  [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]], {}, class: 'select__box'
                    =fa_icon 'angle-down', class: "select__icon"
                    %span{class: "select__span"} 月

                  .content__select
                    = f.select :exp_year, [["17",2017],["18",2018],["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]], {}, class: 'select__box'
                    =fa_icon 'angle-down', class: "select__icon"
                    %span{class: "select__span"} 年

                .content__code
                  = f.label :security_cord, 'セキュリティコード', class: 'label__title'
                  %span{class: "form__text"} 必須
                  = f.text_field :cvc, type: 'text', class: 'input__form', placeholder: 'カード背面4桁もしくは3桁の番号'

                  .bottom__info
                    .bottom__box#card_token
                      %span{class: "bottom__span"} ?
                      カード裏面の番号とは？
                    = f.submit '追加する', class: 'content-bottom--add-btn', id: 'token_submit'



  = render "user_footer"

:javascript
  document.addEventListener(
  "DOMContentLoaded", (e) => {
    Payjp.setPublicKey("pk_test_9becf42708e2062a185a529d");
    const btn = document.getElementById('token_submit'); //IDがtoken_submitの場合に取得されます
    btn.addEventListener("click", (e) => {　//ボタンが押されたときに作動します
      e.preventDefault();　//ボタンを一旦無効化します

      //カード情報生成
      const card = {
        number: document.getElementById("card_number").value,
        cvc: document.getElementById("cvc").value,
        exp_month: document.getElementById("exp_month").value,
        exp_year: document.getElementById("exp_year").value
      }; //入力されたデータを取得します。

      //トークン生成
      Payjp.createToken(card, (status, response) => {
        if (status === 200) { //成功した場合
          $("#card_number").removeAttr("name");
          $("#cvc").removeAttr("name");
          $("#exp_month").removeAttr("name");
          $("#exp_year").removeAttr("name"); //カード情報を自分のサーバにpostせず削除します
          $("#card_token").append(
            $('<input type="hidden" name="payjp-token">').val(response.id)
          ); //トークンを送信できるように隠しタグを生成
          document.inputForm.submit();
          alert("登録が完了しました"); //確認用
        } else {
          alert("カード情報が正しくありません。"); //確認用
        }
      });
    });
  },false);