config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      post 'step2',    to:'signup#save_to_session_step1'
      get 'step3'
      post 'step3',    to:'signup#save_to_session_step2'
      get 'step4'
      post 'step4',    to:'signup#save_to_session_step3'
      get 'done'
    end
  end
  root to: 'items#index'

  resources :items do
    resources :purchase, only: :show do
      member do
        post "pay", to: 'purchase#pay'
      end
    end
  end


  resources :users do
    member do
      get "logout"
      get "profile"
      get "userinfo"
      get "cardlist"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  has_one :address
  has_many :cards
  has_many :items



  def self.from_omniauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        snscredential = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20]
        )
        snscredential = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      end
    end
    return user, snscredential
  end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    info = User.from_omniauth(request.env['omniauth.auth'])
    @user = info[0]
    @snscredential = info[1]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session[:nickname] = @user.nickname
      session[:email] = @user.email
      session[:password] = @user.password
      session[:uid] = @snscredential.uid
      session[:provider] = @snscredential.provider
      redirect_to step1_signup_index_path
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def logout
  end
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @users = User
  end

  def new
  end

  def destroy
  end

  def profile
    @user = User.find(params[:id])
  end
  
  def userinfo
    @user = User.find(params[:id])
  end

  def cardlist
    @user = User.find(params[:id])
  end
  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users-edit-content.html.haml
.edit-wrapper
  .edit-container
    .edit-heading
      %h2 プロフィール
    = form_for(current_user) do |f|
      .edit-container__profile-header
        .edit-container__profile-header__icon
          = image_tag asset_path("sample1.jpg"), width:"60px", height:"60px";
          = f.text_field :nickname, class: "edit-profile"
      .edit-container__content
        %textarea.edit-text
        .edit-container__content__submit
          = f.submit "変更する", class: "mypage_submit"

app/views/users/_users-information.html.haml
.mypage-information
  .mypage-information__header
    = link_to "" do
      .mypage-information__header__profile
        = image_tag asset_path("sample1.jpg"), width:"60px", height:"60px"
        = simple_format @user.nickname
        .mypage-information__header__profile__transaction
          %p
            評価 
            %span 100
          %p
            出品数 
            %span 100
  .mypage-information__container
    .mypage-information__container__heading
      = link_to users_path(current_user) do
        %ul
          %li
            %input#mypage-heading1{:type => "button", :value => "お知らせ"}/
          %li
            %input#mypage-heading2{:type => "button", :value => "やることリスト"}/
    #mypage-content.mypage-information__container__contents
      = link_to "" do
        .mypage-information__container__contents__content
          = image_tag "sample1.jpg", width:"48px", height:"48px"
          .mypage-information__container__contents__content__detail
            %p いいねしました。
            %time.mypage-time
              %i.fa.fa-clock{"aria-hidden" => "true"}
              %p 22時間
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
      .mypage-information__container__contents__content__go
        = link_to  do
          %input#mypage-details{:type => "button", :value => "一覧を見る"}/
  .mypage-information__container
    %h3 購入した商品
    .mypage-information__container__heading
      = link_to users_path(current_user) do
        %ul
          %li
            %input#mypage-heading1{:type => "button", :value => "取引中"}/
          %li
            %input#mypage-heading2{:type => "button", :value => "過去の取引"}/
    #mypage-content.mypage-information__container__contents
      = link_to "" do
        .mypage-information__container__contents__content
          = image_tag "sample1.jpg", width:"48px", height:"48px"
          .mypage-information__container__contents__content__detail
            %p 取引が完了しました
            %p 取引完了
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
        .mypage-information__container__contents__content__go
          = link_to  do
            %input#mypage-details{:type => "button", :value => "一覧を見る"}/

app/views/users/_users-navigation.html.haml
.navigation
  .navigation__container
    .navigation__container__content
      = render "shared/breadcrumbs"

app/views/users/_users-sidebar.html.haml
.mypage-sidebar
  .mypage-sidebar__container
    = link_to user_path(current_user) do
      #sidebar-active.mypage-sidebar__container__title
        %h2.weight マイページ
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 お知らせ
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 やることリスト
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 いいね！一覧
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to new_item_path do
      .mypage-sidebar__container__title
        %h2 出品する
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 出品した商品・出品中
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 出品した商品・取引中
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 出品した商品・売却済み
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 購入した商品・取引中
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 出品した商品・過去の取引
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 ニュース一覧
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 評価一覧
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 ガイド
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    = link_to  do
      .mypage-sidebar__container__title
        %h2 お問い合わせ
        %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    .sidebar-settlement
      　
      %p メルペイ
      = link_to  do
        .mypage-sidebar__container__title
          %h2 残高・振込申請
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
      = link_to  do
        .mypage-sidebar__container__title
          %h2 ポイント
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
    .sidebar-config
      %p 設定
      = link_to profile_user_path(current_user) do
        .mypage-sidebar__container__title
          %h2 プロフィール
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
      = link_to  do
        .mypage-sidebar__container__title
          %h2 発送元・お届け先住所変更
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
      = link_to cardlist_user_path(current_user) do
        .mypage-sidebar__container__title
          %h2 支払い方法
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
      = link_to  do
        .mypage-sidebar__container__title
          %h2 メール/パスワード
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
      = link_to userinfo_user_path(current_user) do
        .mypage-sidebar__container__title
          %h2 本人情報
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
      = link_to  do
        .mypage-sidebar__container__title
          %h2 電話番号の確認
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
      = link_to logout_user_path(current_user) do
        .mypage-sidebar__container__title
          %h2 ログアウト
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}

app/views/users/cardlist.html.haml
= render 'items/header.show'
= render "users-navigation"
.mypage-container
  = render 'users/users-sidebar'
  .mypage-cardlist-content
    %section.content-chapter
      %h2.content-chapter__head 支払い方法
      .content-chapter__single-inner
        .single-conent
          %h3.single-content__sub-head クレジットカード一覧
        %ul.payment-list
          %li
            %form.single-inner__content
              %figure
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2356214421", width: "49", height: "20" 
              .settings-payment-num ************4242
              .settings-payment-num 12/20
              %button.settings-payment-remove 削除する
        .settings-not-regist
          = link_to '#', class: 'payment-method' do
            %span 支払い方法について
            %i.fas.fa-angle-right
= image_tag 'top-page-header.jpg', class: 'footer-image'
= render '/items/footer'

app/views/users/edit.html.haml
= render '/items/header'
= render "users-navigation"
.users-edit
  .users-edit__wrap
    = render "users/users-sidebar"
    = render "users/users-edit-content"
= render '/items/footer' 

app/views/users/index_header.haml
.header
  %h1
    %a{href: '#'}
      %img{src: 'fmarket_logo_red.svg', alt: "Fmarket"}

  %nav.header__progress-bar
    %ol.header__progress-bar__list
      %li.header__progress-bar__list__item
        %span 会員情報
        .header__progress-bar__list__item__status{id: "progress-bar_active"}
      %li.header__progress-bar__list__item
        電話番号認証
        .header__progress-bar__list__item__status
      %li.header__progress-bar__list__item
        お届け先住所入力
        .header__progress-bar__list__item__status
      %li.header__progress-bar__list__item
        支払い方法
        .header__progress-bar__list__item__status
      %li
        完了
        .header__progress-bar__last

app/views/users/logout.html.haml
.main
  = render 'items/header.show'
  = render "users-navigation"
.mypage
  .mypage__main
    = render 'users/users-sidebar'
    .single-main 
      .single-inner
        .btn
        = link_to destroy_user_session_path, method: :delete do
          %button{type:"submit",class:"btn-red"}
            ログアウト
.foot 
  = image_tag 'top-page-header.jpg', class: 'footer-image'
  = render 'items/footer'

app/views/users/profile.html.haml
= render '/items/header.show'
= render "users-navigation"
.users-edit
  .users-edit__wrap
    = render "users/users-sidebar"
    = render "users/users-edit-content"
= image_tag 'top-page-header.jpg', class: 'footer-image'
= render '/items/footer' 

app/views/users/show.html.haml
= render '/items/header.show'
= render "users-navigation"

.mypage
  .mypage__main
    = render "users-sidebar"
    = render "users-information"
= image_tag 'top-page-header.jpg', class: 'footer-image'
= render '/items/footer'

app/views/users/userinfo.html.haml
= render '/items/header.show'
= render "users-navigation"

.mypage
  .mypage__main
    = render "users/users-sidebar"
    
    .mypage-registration
      .mypage-registration__heading
        %h1 本人情報の登録
      .mypage-registration__container
        .mypage-registration__container__document
          %h2 お客さまの本人情報をご登録ください。<br>登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          %i.fa.fa-chevron-right{"aria-hidden" => "true"}
          = link_to "本人確認書類のアップロードについて","", class: "mypage-registration-document"
        .mypage-registration__container__content
          .mypage-registration__container__content__person
            %h2 お名前
            = simple_format @user.family_name + @user.first_name
          .mypage-registration__container__content__person
            %h2 お名前カナ
            = simple_format @user.family_name_kana + @user.first_name_kana
          .mypage-registration__container__content__person
            %h2 生年月日
            = simple_format "#{@user.birthdate_year}/#{@user.birthdate_month}/#{@user.birthdate_day}"
          .mypage-registration__container__content__form
            = form_for(current_user) do |f|
              .mypage-registration__container__content__person
                %h2 郵便番号
                = text_field :postal_code, class: "mypage_postal_code", placeholder: '(例)1234567'
              .mypage-registration__container__content__person
                %h2 都道府県
                = text_field :prefectures, class: "mypage_prefectures", placeholder: '(例)1234567'
              .mypage-registration__container__content__person
                %h2 市区町村
                = text_field :city, class: "mypage_city", placeholder: '(例)横浜市緑区'
              .mypage-registration__container__content__person
                %h2 番地
                = text_field :house＿number, class: "mypage_house_number",placeholder: '(例)青山1-1-1'
              .mypage-registration__container__content__person
                %h2 建物名
                = text_field :building_name, class: "mypage_building_name",placeholder: '(例)柳ビル103'
              .mypage-registration__container__content__submit
                = f.submit "登録する", class: "mypage_submit"
          .mypage-registration__container__footer
            %i.fa.fa-chevron-right{"aria-hidden" => "true"}
            = link_to "本人情報の登録について","", class: "mypage-registration-document"
= image_tag 'top-page-header.jpg', class: 'footer-image'
= render '/items/footer'