config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      post 'step2',    to:'signup#save_to_session_step1'
      get 'step3'
      post 'step3',    to:'signup#save_to_session_step2'
      get 'step4'
      post 'step4',    to:'signup#save_to_session_step3'
      get 'done'
    end
  end
  root to: 'items#index'

  resources :items do
    resources :purchase, only: :show do
      member do
        post "pay", to: 'purchase#pay'
      end
    end
  end


  resources :users do
    member do
      get "logout"
      get "profile"
      get "userinfo"
      get "cardlist"
    end
  end

end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  before_action :set_card, :set_item

  def show
    if current_user.id === @item.seller_id 
      redirect_to root_path
    end
    unless @item.buyer_id === nil
      redirect_to root_path
    end
    Payjp.api_key = ENV["PAYJP_TEST_SECRET_KEY"]
    customer = Payjp::Customer.retrieve(@card.customer_id)
    @default_card_information = customer.cards.retrieve(@card.card_id)
  end

  def pay
    if current_user.id === @item.seller_id || @item.buyer_id != nil
      redirect_to root_path
    else
      Payjp.api_key = ENV["PAYJP_TEST_SECRET_KEY"]
      Payjp::Charge.create(
        :amount => @item.price,
        :customer => @card.customer_id,
        :currency => 'jpy',
      )
      item = Item.find(params[:id])
      item.update_attributes(buyer_id: current_user.id)

      redirect_to root_path, notice: "#{@item.name}を購入しました。"
    end
  end

private
  def set_card
    @card = Card.find_by(user_id: current_user)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/views/purchase/show.html.haml
.items-buy
  .items-buy__header
    .items-buy__header__image
      = image_tag asset_path("fmarket_logo_red.svg"), width: "185px", height: "50px"
  .items-buy-container
    .items-buy-container__heading
      %p 購入内容の確認
    .items-buy-container__content
      .items-buy-container__content__show
        .items-buy-container__content__show__image
          = image_tag @item.images.first, width:"80px", height: "80px"
        .items-buy-container__content__show__details
          %p #{@item.name}
          %p ¥#{@item.price}
          %p (税込) 送料込み
    .items-buy-container__settlement
      .items-buy-container__settlement__wrap
        = form_for @item, url: pay_item_purchase_path(@item), method: :post do |f|
          .items-buy-container__settlement__wrap__price
            %ul
              %li 支払い金額
              %li  ¥#{@item.price}
          .items-buy-container__settlement__wrap__input
            %label
              %input{type:"cheakbox"}
              %p ポイントを使用 (所持ポイント: P0)
          .items-buy-container__settlement__wrap__credit
            = link_to "変更する", ""
            %ul
              %li.font-weight 支払い方法
              %li クレジットカード
              %li ***********2019
              %li 有効期限 12/21
              %li
                = image_tag asset_path(""), width: "50px", height: "15px"
          .items-buy-container__settlement__wrap__delivery
            = link_to "変更する", ""
            %ul
              %li.font-weight 配送先
              %li 〒666-6666
              %li 大阪市 北区 大阪町 999-9
              %li エキスパート太郎
              %li
          .items-buy-container__settlement__wrap__submit
            = f.submit '購入する', class: 'buy-btn'
    = render 'signup/user_footer'