config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      post 'step2',    to:'signup#save_to_session_step1'
      get 'step3'
      post 'step3',    to:'signup#save_to_session_step2'
      get 'step4'
      post 'step4',    to:'signup#save_to_session_step3'
      get 'done'
    end
  end
  root to: 'items#index'

  resources :items do
    resources :purchase, only: :show do
      member do
        post "pay", to: 'purchase#pay'
      end
    end
  end


  resources :users do
    member do
      get "logout"
      get "profile"
      get "userinfo"
      get "cardlist"
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :images 
  validates :name, :description, :category, :condition, :feepayer, :method, :region_id, :days, :price, presence: true

  belongs_to :seller, class_name: "User"
  belongs_to :buyer, optional:true, class_name: "User"
  
  validate :images_validate
  validate :image_max_length


  def images_validate
    unless images.attached?
      errors.add(:images, '画像を入れてください')
    end
  end
  
  def image_max_length
    unless images.length <= 10
      errors.add(:images, '画像を10枚以内にしてください')
    end
  end
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :region, class_name: 'Prefecture'

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show, :destroy, :buy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @items = Item.where(buyer_id: nil)
  end
  
  def new
    @item = Item.new
  end

  def buy
    @items = Item.all
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render new_item_path
    end
  end 
  
  def edit
    unless current_user.id === @item.seller_id
      redirect_to root_path
    end
  end

  def update
    if current_user.id === @item.seller_id
      if @item.update(item_params)
        redirect_to root_path
      else
        render edit_item_path
      end
    else
      redirect_to root_path
    end
  end
  
  def show
    @item = Item.find(params[:id])
  end

  def destroy
    if current_user.id === @item.seller_id
      if @item.destroy
        attachments = ActiveStorage::Attachment.where(id: params[:deleted_img_ids])
        attachments.map(&:purge)
        redirect_to root_path
      else
        render items_path
      end
    else
      redirect_to root_path
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :condition, :feepayer, :method, :region_id, :category, :days, :price, :image, images: []).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
%footer
  .footer__main
    .footer__lists-above
      %ul.company__lists
        %li.title__list メルカリについて
        %li
          = link_to '会社概要 (運営会社)', '#'
        %li
          = link_to '採用情報', '#'
        %li
          = link_to 'プレリリース', '#'
        %li
          = link_to '公式ブログ', '#'
        %li
          = link_to 'メルカリロゴ利用ガイドライン', '#'
        %ul.sns-icons
          %li
            %a{href: 'https://twitter.com', target: '_blank', class: 'twitter-icon'}
              %i.fab.fa-twitter
          %li
            %a{href: 'https://facebook.com', target: '_blank', class: 'facebook-icon'}
              %i.fab.fa-facebook-square

      %ul.help__lists
        %li.title__list ヘルプ＆ガイド
        %li
          = link_to 'メルカリガイド', '#'
        %li
          = link_to 'らくらくメルカリ便', '#'
        %li
          = link_to 'ゆうゆうメルカリ便', '#'
        %li
          = link_to '大型メルカリ便', '#'
        %li
          = link_to '車体取引ガイド', '#'
        %li
          = link_to 'メルカリあんしん・あんぜん宣言!', '#'
        %li
          = link_to '偽ブランド品撲滅への取り組み', '#'
        %li
          = link_to 'メルカリボックス', '#'
      %ul.privacy__lists
        %li.title__list プライバシーと利用規約
        .privacy__lists-main
          %ul.privacy__lists-left
            %li
              = link_to 'プライバシーポリシー', '#'
            %li
              = link_to 'メルカリ利用規約', '#'
            %li
              = link_to 'あんしんスマホサポート制度に関する利用特約', '#'
            %li
              = link_to 'コンプライアンスポリシー', '#'
          %ul.privacy__lists-right
            %li
              = link_to '個人データのあんぜん管理に係る基本方針', '#'
            %li
              = link_to '特定商取引に関する表記', '#'
            %li
              = link_to '資金決算法に基づく表示', '#'
            %li
              = link_to '法令順守と犯罪防止のために', '#'
      %ul.country__lists
        %li.title__list 国
        %li
          = link_to '日本', '#'
        %li
          = link_to 'United States', '#'
    .footer-copyright-below
      .footer-main
        = link_to root_path do
          = image_tag asset_path("fmarket_logo_white.svg"), class: 'footer-logo'
        %p.copyright © Mercari, Inc.

app/views/items/_header.html.haml
%header
  .top-page__header
    .top-page__header-above
      = link_to root_path do
        = image_tag asset_path("fmarket_logo_red.svg"), class: 'header-logo'
      %input{tepe: 'text', placeholder: '何かお探しですか?', class: 'search-box'} 
      %i.fas.fa-search
    .top-page__header-below
      .top-page__header-below-left
        .search__lists
          .search__list-right
            %a{href: '#'}
              %i.fas.fa-list
              カテゴリーから探す
          .search__list-left
            %a{href: '#'}
              %i.fas.fa-tags
              ブランドから探す
      .top-page__header-below-right
        = link_to '新規会員登録', signup_index_path, method: :get, class: 'sign-up-btn'
        = link_to 'ログイン', new_user_session_path, class: 'sign-in-btn'

app/views/items/_header.index.html.haml
%header
  .top-page__header
    .top-page__header-above
      %img.header-logo{src: 'fmarket_logo_red.svg'}
      %input{tepe: 'text', placeholder: '何かお探しですか?', class: 'search-box'} 
      %i.fas.fa-search
    .top-page__header-below
      .top-page__header-below-left
        .search__lists
          .search__list-right
            %a{href: '#'}
              %i.fas.fa-list
              カテゴリーから探す
          .search__list-left
            %a{href: '#'}
              %i.fas.fa-tags
              ブランドから探す
      .top-page__header-below-right
        = link_to '新規会員登録', '#', class: 'sign-up-btn'
        = link_to 'ログイン', '#', class: 'sign-in-btn'

app/views/items/_header.new.html.haml
.new-page__header
  = link_to root_path do
    = image_tag 'fmarket_logo_red.svg', class: 'new-page__header-logo'

app/views/items/_header.show.html.haml
%header
  .show-page__header
    .show-page__header-above
      = link_to root_path do
        = image_tag 'fmarket_logo_red.svg', class: 'header-logo'
      %input{tepe: 'text', placeholder: '何かお探しですか?', class: 'search-box'} 
      %i.fas.fa-search
    .show-page__header-below
      .show-page__header-below-left
        .search__lists
          .search__list-right
            %a{href: '#'}
              %i.fas.fa-list
              カテゴリーから探す
          .search__list-left
            %a{href: '#'}
              %i.fas.fa-tags
              ブランドから探す
      .show-page__header-below-right
        = link_to '#' do
          %i.far.fa-heart
          いいね！一覧
        = link_to '#' do
          %i.far.fa-bell
          お知らせ
        = link_to '#' do
          %i.fas.fa-check
          やることリスト
        = link_to user_path(current_user) do
          %i.far.fa-user-circle
          マイページ

app/views/items/_main.html.haml
.main
  .bg__header
    .main__header
      .main__header-text
        %h1 商品一覧
      .main__header-lists
        %ul.categories
          %li
            = link_to 'レディース', '#'
          %li
            = link_to 'メンズ', '#'
          %li
            = link_to '家電・スマホ・カメラ', '#'
          %li
            = link_to 'おもちゃ・ホビー・グッズ', '#'
  .bg__contents
    .main__contents
      .main__contents-text
        %h1 新着アイテム
        = link_to '#', class: 'view__content' do
          %p もっと見る
          %i.fas.fa-arrow-right
      %ul.main__contents-lists
        - @items.each do |item|
          %li.main__content
            = link_to item_path(item), class: 'content__anchor' do
              .content-above
                = image_tag item.images.first, class: 'content__image'
                = tag.span item.price, class: 'content__price'
              .content-below
                = simple_format item.description, class: 'content__text'

app/views/items/buy.html.haml
.items-buy
  .items-buy__header
    .items-buy__header__image
      = image_tag asset_path("fmarket_logo_red.svg"), width: "185px", height: "50px"
  .items-buy-container
    .items-buy-container__heading
      %p 購入内容の確認
    .items-buy-container__content
      .items-buy-container__content__show
        .items-buy-container__content__show__image
          - if @item.image.attached?
            = image_tag url_for(@item.image.attach(image)), width:"80px", height: "80px"
        .items-buy-container__content__show__details
          %p #{@item.name}
          %p ¥#{@item.price}
          %p (税込) 送料込み
    .items-buy-container__settlement
      .items-buy-container__settlement__wrap
        = form_for(@item, url: item_path(@item)) do |f|
          .items-buy-container__settlement__wrap__price
            %ul
              %li 支払い金額
              %li  ¥#{@item.price}
          .items-buy-container__settlement__wrap__input
            %label
              %input{type:"cheakbox"}
              %p ポイントを使用 (所持ポイント: P0)
          .items-buy-container__settlement__wrap__credit
            = link_to "変更する", ""
            %ul
              %li.font-weight 支払い方法
              %li クレジットカード
              %li ***********2019
              %li 有効期限 12/21
              %li
                = image_tag asset_path("Visa_2014_logo_detail.svg.png"), width: "50px", height: "15px"
          .items-buy-container__settlement__wrap__delivery
            = link_to "変更する", ""
            %ul
              %li.font-weight 配送先
              %li 〒666-6666
              %li 大阪市 北区 大阪町 999-9
              %li エキスパート太郎
              %li
          .items-buy-container__settlement__wrap__submit
            = f.submit '購入する', class: 'buy-btn'
    = render 'signup/user_footer'

app/views/items/edit.html.haml
.new-page
  = render 'header.new'
  .new-page__main.edit-page__main
    .new-page__main-forms
      .new-page__main-forms__header
        %h1 商品の状態を入力
      .new-page__main__form
        = form_for(@item, url: item_path(@item)) do |f|
          = render 'layouts/error_messages', model: f.object
          %h1 出品画像 
          %span 必須
          %p 最大10枚までアップロードできます
          .item-num-0#image_box__container
            = f.label :images, class: 'form__mask__image' do
              = f.file_field :images, multiple: true, class: 'image__form'
            .image-placeholder
              %h3 ドラッグアンドドロップ
              %h3 またはクリックしてファイルをアップロード
          .new-page__main__form.item__form
            %h1 商品名
            %span 必須
            = f.text_field :name, placeholder: '商品名 (必須40文字まで)', class: 'item-name__form'
            %h1 商品の説明
            %span 必須
            = f.text_area :description, placeholder: '商品の説明 (必須1,000文字以内) (色、素材、重さ、定価、注意点など)  例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', class: 'item-description__form'
          .new-page__main__form.item-details
            .form-left
              %p 商品の詳細
            .form-right
              %h1 カテゴリー
              %span 必須
              = f.select :category, ["レディース","メンズ","ベビー・キッズ","インテリア・住まい・小物","本・音楽・ゲーム","おもちゃ・ホビー・グッズ","コスメ・香水・美容","家電・スマホ・カメラ","スポーツ・レジャー","ハンドメイド","チケット","自転車・オートバイ","その他"], {prompt: "---"}, {class: 'select'}
              %h1 商品の状態
              %span 必須           
              = f.select :condition, ["新品","未使用","未使用に近い","目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"], {prompt: "---"}, {class: 'select'}
          .new-page__main__form.about-postage
            .form-left
              %p 配送について
              = link_to '#' do
                %i.fas.fa-question-circle
            .form-right
              %h1 配送料の負担
              %span 必須
              = f.select :feepayer, ["送料込み(出品者負担)","着払い(購入者負担)"], {prompt: "---"}, {class: 'select'}
              %h1 配送の方法
              %span 必須
              = f.select :method, ["未定","らくらくメルカリ便","ゆうメール","レターパック","クロネコヤマト","ゆうパック","クリップポスト","ゆうパケット"], {prompt: "---"}, {class: 'select'}
              %h1 配送元の地域
              %span 必須
              = f.collection_select :region_id, Prefecture.all, :id, :name, prompt: "---", class: 'input'
              %h1 発送までの日数
              %span 必須
              = f.select :days, ["1〜2日で発送", "2〜3日で発送", "4〜7日で発送"], {prompt: "---"}, {class: 'select'}
          .new-page__main__form.about-price
            .form-left
              %p 販売価格(300〜9,999,999)
              = link_to '#' do
                %i.fas.fa-question-circle
            .form-right
              .form-right-top
                %h1 価格
                %span 必須
                %p ¥
                = f.number_field :price, placeholder: '例) 300', class: 'input-price'
              .form-right-middle
                %p 販売手数料(10%)
                %h2 -
              .form-right-bottom
                %h1 販売利益
                %p -
          .new-page__main__form.edit-item
            = f.submit '編集する', class: 'edit-btn'
            = link_to 'キャンセルする', '#', class: 'back-btn'

:javascript
  $(function() {
    var dataBox = new DataTransfer();
    var file_field = document.querySelector('input[type="file"]')
    $('.image__form').change(function() {
      var file = $('input[type="file"]').prop('files')[0];
      $.each(this.files, function(i, file){
        var fileReader = new FileReader();
        dataBox.items.add(file)
        file_field.files = dataBox.files
        var num = $('.item-image').length + 1 + i
        fileReader.readAsDataURL(file);
        if (num == 5){
          $('#image_box__container').css('display', 'none')   
        }
        if ( num >= 5) {
          $('#image_box__container').css('display', 'none')
        }
        fileReader.onloadend = function() {
          var src = fileReader.result
          var html= `<div class='item-image' data-image="${file.name}">
                      <div class=' item-image__content'>
                        <div class='item-image__content--icon'>
                          <img src=${src} width="113" height="130">
                        </div>
                      </div>
                      <div class='item-image__operation'>
                        <div class='item-image__operation--edit'>編集</div>
                        <div class='item-image__operation--delete'>削除</div>
                      </div>
                    </div>`
          $('#image_box__container').before(html);
        };
        $('#image_box__container').attr('class', `item-num-${num}`)
      });
    });
    $(document).on("click", '.item-image__operation--delete', function(){
      var target_image = $(this).parent().parent()
      var target_name = $(target_image).data('image')
      if(file_field.files.length==1){
        $('input[type="file"]').val(null)
        dataBox.clearData();
      }else{
        $.each(file_field.files, function(i,input){
          if(input.name==target_name){
            dataBox.items.remove(i) 
          }
        })
        file_field.files = dataBox.files
      }
      target_image.remove()
      var num = $('.item-image').length
      $('#image_box__container').show()
      $('#image_box__container').attr('class', `item-num-${num}`)
    });
  });

app/views/items/index.html.haml
= render 'layouts/flash'
.top-page
  - if user_signed_in?
    =  render 'header.show'
  - else
    = render 'header'
  .top-page__header-image
    = image_tag 'top-page-header.jpg', class: 'header-image'
  .top-page__section-pic
  = render 'main'
  = link_to new_item_path, class: 'red-btn' do
    %p 出品
    %i.fas.fa-camera
  .top-page__footer-image
    = image_tag 'top-page-header.jpg', class: 'footer-image'
  = render 'footer'

app/views/items/new.html.haml
.new-page
  = render 'header.new'
  .new-page__main
    .new-page__main-forms
      .new-page__main-forms__header
        %h1 商品の状態を入力
      .new-page__main__form
        = form_for(@item, url: items_path) do |f|
          = render 'layouts/error_messages', model: f.object
          %h1 出品画像 
          %span 必須
          %p 最大10枚までアップロードできます
          .item-num-0#image_box__container
            = f.label :images, class: 'form__mask__image' do
              = f.file_field :images, multiple: true, value: "", class: 'image__form'
              .image-placeholder
                %h3 ドラッグアンドドロップ
                %h3 またはクリックしてファイルをアップロード
          .new-page__main__form.item__form
            %h1 商品名
            %span 必須
            = f.text_field :name, placeholder: '商品名 (必須40文字まで)', class: 'item-name__form'
            %h1 商品の説明
            %span 必須
            = f.text_area :description, placeholder: '商品の説明 (必須1,000文字以内) (色、素材、重さ、定価、注意点など)  例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', class: 'item-description__form'
          .new-page__main__form.item-details
            .form-left
              %p 商品の詳細
            .form-right
              %h1 カテゴリー
              %span 必須
              = f.select :category, ["レディース","メンズ","ベビー・キッズ","インテリア・住まい・小物","本・音楽・ゲーム","おもちゃ・ホビー・グッズ","コスメ・香水・美容","家電・スマホ・カメラ","スポーツ・レジャー","ハンドメイド","チケット","自転車・オートバイ","その他"], {prompt: "---"}, {class: 'select'}
              %h1 商品の状態
              %span 必須           
              = f.select :condition, ["新品","未使用","未使用に近い","目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"], {prompt: "---"}, {class: 'select'}
          .new-page__main__form.about-postage
            .form-left
              %p 配送について
              = link_to '#' do
                %i.fas.fa-question-circle
            .form-right
              %h1 配送料の負担
              %span 必須
              = f.select :feepayer, ["送料込み(出品者負担)","着払い(購入者負担)"], {prompt: "---"}, {class: 'select'}
              %h1 配送の方法
              %span 必須
              = f.select :method, ["未定","らくらくメルカリ便","ゆうメール","レターパック","クロネコヤマト","ゆうパック","クリップポスト","ゆうパケット"], {prompt: "---"}, {class: 'select'}
              %h1 配送元の地域
              %span 必須
              = f.collection_select :region_id, Prefecture.all, :id, :name, prompt: "---", class: 'input'
              %h1 発送までの日数
              %span 必須
              = f.select :days, ["1〜2日で発送", "2〜3日で発送", "4〜7日で発送"], {prompt: "---"}, {class: 'select'}
          .new-page__main__form.about-price
            .form-left
              %p 販売価格(300〜9,999,999)
              = link_to '#' do
                %i.fas.fa-question-circle
            .form-right
              .form-right-top
                %h1 価格
                %span 必須
                %p ¥
                = f.number_field :price, placeholder: '例) 300', class: 'input-price'
              .form-right-middle
                %p 販売手数料(10%)
                %h2 -
              .form-right-bottom
                %h1 販売利益
                %p -
          .new-page__main__form.sell-item
            %p.line-1
              = link_to '禁止されている出品', '#'
              %p 、
              = link_to '行為', '#'
              %p を必ずご確認ください。
            %p.line-2
              %p またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to '偽ブランドの販売', '#'
              %p は犯罪であり処罰される可能性があります。
            %p.line-4
              %p また、出品をもちまして
              = link_to '加盟店規約', '#'
              %p に同意したことになります。
              = f.submit '出品する', class: 'sell-btn'
              = link_to 'もどる', '#', class: 'back-btn'
= render 'signup/user_footer'

:javascript
  $(function() {
    var dataBox = new DataTransfer();
    var file_field = document.querySelector('input[type="file"]')
    $('.image__form').change(function() {
      var file = $('input[type="file"]').prop('files')[0];
      $.each(this.files, function(i, file){
        var fileReader = new FileReader();
        dataBox.items.add(file)
        file_field.files = dataBox.files
        var num = $('.item-image').length + 1 + i
        fileReader.readAsDataURL(file);
        if (num == 5){
          $('#image_box__container').css('display', 'none')   
        }
        fileReader.onloadend = function() {
          var src = fileReader.result
          var html= `<div class='item-image' data-image="${file.name}">
                      <div class=' item-image__content'>
                        <div class='item-image__content--icon'>
                          <img src=${src} width="113" height="130">
                        </div>
                      </div>
                      <div class='item-image__operation'>
                        <div class='item-image__operation--edit'>編集</div>
                        <div class='item-image__operation--delete'>削除</div>
                      </div>
                    </div>`
          $('#image_box__container').before(html);
        };
        $('#image_box__container').attr('class', `item-num-${num}`)
      });
    });
    $(document).on("click", '.item-image__operation--delete', function(){
      var target_image = $(this).parent().parent()
      var target_name = $(target_image).data('image')
      if(file_field.files.length==1){
        $('input[type="file"]').val(null)
        dataBox.clearData();
      }else{
        $.each(file_field.files, function(i,input){
          if(input.name==target_name){
            dataBox.items.remove(i) 
          }
        })
        file_field.files = dataBox.files
      }
      target_image.remove()
      var num = $('.item-image').length
      $('#image_box__container').show()
      $('#image_box__container').attr('class', `item-num-${num}`)
    });
  });

app/views/items/show.html.haml
.item-show-page
  - if user_signed_in?
    = render 'header.show'
  - else 
    = render 'header'
  .main
    .main-item-details
      .main-item__header
        = simple_format @item.name
      .main-item
        .main-item-left-pic
          = image_tag @item.images.first, class: 'main-pic'
          - @item.images.each do |image|
            = image_tag image, class: 'sub-pic'
        .main-item-right-detail
          %table
            %tr
              %th 出品者
              %td
                = link_to '#' do
                  = @item.seller.nickname
                .three-faces
                  %i.fas.fa-grin
                  %span 29
                  %i.fas.fa-meh
                  %span 0
                  %i.fas.fa-frown
                  %span 0
            %tr
              %th カテゴリー
              %td

                = link_to '#', class: 'category-text' do
                  = @item.category
                = link_to '#', class: 'category-text' do
                  = @item.category
                = link_to '#', class: 'category-text' do
                  = @item.category
            %tr
              %th ブランド
              %td
                = link_to 'コーチ', '#'
            %tr
              %th 商品の状態
              %td
                = simple_format @item.condition
            %tr
              %th 配送料の負担
              %td
                = simple_format @item.feepayer
            %tr
              %th 配送の方法
              %td
                = simple_format @item.method
            %tr
              %th 配送元地域
              %td
                = link_to '#' do
                  = @item.region.name
            %tr
              %th 発送日の目安
              %td
                = @item.days
      .item-price
        %h1
          = @item.price
          %span (税込)
          %span.postage 送料込み
        - if user_signed_in? && current_user.id == @item.seller_id
          = link_to '商品の編集', edit_item_path(@item), class: 'item-edit-btn'
          %p.item-select-or or
          = link_to '出品を一旦停止する', '#', class: 'item-stop-btn'
          = link_to 'この商品を削除する', item_path(@item.id), method: :delete, class: 'item-delete-btn'
        - else
          = link_to '購入画面に進む', item_purchase_path(@item), method: :get, class: 'buy-btn'
      .item-description
        = simple_format @item.description, class: 'item-description'
        .item-description--below
          = link_to '#', class: 'gray-links-good' do
            %i.far.fa-heart
            いいね! 0
          = link_to '#', class: 'gray-links-report' do
            %i.far.fa-flag
            不適切な商品の報告
          = link_to '#', class: 'blue-link' do
            %i.fas.fa-lock
            あんしん・あんぜんへの取り組み



    .comment
      .comment-attention
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .comment-area
        %textarea
        = link_to 'コメントする', '#', class: 'comment-btn'
    .other-items-link
      .left-item-link
        %i.fas.fa-chevron-left
        = link_to '【最終値下げ】レプシィム リボン付きスエードフラットシューズ/ブラック Mサイズ', '#'
      .right-item-link
        = link_to '始虹帝 ミノガミ 秘22枚', '#'
        %i.fas.fa-chevron-right



    .show-page-sns
      .show-page-sns-icons
        .facebook
          = link_to 'https://facebook.com', target: '_blank' do
            %i.fab.fa-facebook-square
        .twitter
          = link_to 'https://twitter.com', target: '_blank' do
            %i.fab.fa-twitter-square
        .pinterest
          = link_to 'https://pinterest.jp', target: '_blank' do
            %i.fab.fa-pinterest-square

    %p.items-box__header 
      = link_to "#{@item.seller.nickname}さんのその他の出品", '#'
    .user-items
      %ul.items-box
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample1.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample2.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample1.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample2.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample1.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0


    %p.items-box__header 
      = link_to 'コーチのショルダーバッグ その他の商品', '#'
    .user-items
      %ul.items-box
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample1.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample2.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample1.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample2.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
        %li.item-box
          = link_to '#', class: 'item__anchor' do
            .item-above
              %img{src: 'assets/sample1.jpg', class: 'item__image'}
            .item-below
              %p.item__text 財布です。
              .item-below-price
                %span.price ¥60,000
                %i.far.fa-heart
                  %span 0
= image_tag 'top-page-header.jpg', class: 'footer-image'
= render '/items/footer' 

app/views/items/sold.html.haml
.sold__content
  .header
    = render 'items/header.new'
  .contents
    .content__head
      %p 商品は既に売り切れています
    .content__box
      = link_to '#', class: "link__return" do
        商品画面へ戻る
.footer